name = "ukraine-will-stand"
type = "javascript"
account_id = "c88bfe7bea6d11e0b8db4b5b83b14c38"
usage_model = "unbound"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-25"

kv_namespaces = [
  {binding = "KV", id = "8a198da8ef444da1803589d0ad537e89", preview_id = "8a198da8ef444da1803589d0ad537e89"}
]

[build]
command = "yarn build"

[build.upload]
format = "modules"
main = "./dist/worker.mjs"
